pub mod boost;
pub mod caller;
mod caller_extract;
pub mod cache;
pub mod cache_helpers;
mod default;
mod default_trait;
pub mod intent;
mod navigation_impl;
mod navigation_structure;
mod search_impl;
mod search_impl_rank;
pub mod structure_query;
mod structure_query_match;
mod symbol_info;
pub mod structure_search;
mod structure_search_parse;
mod traits;
pub mod types;
pub mod types_navigation;

pub use default::DefaultSearchService;
pub use traits::SearchService;
