pub mod claude_poll;
pub mod claude_request;
pub mod claude_request_agent;
pub mod enhance_poll;
pub mod git_poll;
pub mod git_poll_watcher;
mod getters_claude;
mod getters_input;
mod getters_picker;
mod getters_ui;
pub mod handlers;
mod key_dispatch;
pub mod mcp_discovery_poll;
pub mod memory_save;
pub mod parser_agent;
pub mod parser_agent_header;
pub mod parser_agent_response;
mod parser_agent_tag;
mod parser_interleave;
pub mod parser;
mod state;
pub mod tool_poll;

pub use state::App;
